package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CallWrapper call wrapper
// swagger:model CallWrapper
type CallWrapper struct {

	// Call ID.
	// Required: true
	// Read Only: true
	Call string `json:"call"`
}

// Validate validates this call wrapper
func (m *CallWrapper) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCall(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CallWrapper) validateCall(formats strfmt.Registry) error {

	if err := validate.RequiredString("call", "body", string(m.Call)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CallWrapper) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CallWrapper) UnmarshalBinary(b []byte) error {
	var res CallWrapper
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
